steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        # Menavigasi ke folder yang tepat dan melakukan deploy
        cd authAPI
        gcloud app deploy app.yaml --quiet
timeout: '1600s'